README.md, app/jobs/resolution_update_export_job..rb, app/jobs/usage_update_export_job.rb, app/models/resolution_update..rb, app/models/usage_update.rb, app/workers/usage_update_import_worker.rb, config/shoryuken.yml, spec/jobs/usage_update_export_job_spec.rb, spec/models/resolution_update_spec.rb, spec/models/usage_update_spec.rb, spec/workers/usage_update_import_worker_spec.rb
child https://github.com/datacite/toccatore/issues/6
=> Feature worker usage update

app/models/concerns/helpable.rb, app/models/related_identifier.rb, spec/concerns/helpable_spec.rb, spec/fixtures/datacite_event.json
the format of obj and subj will look like this 
"subj" => {
"pid" => "https://doi.org/10.17863/cam.12119", 
"type" => "ScholarlyArticle"
},
"obj" => {
"pid" => "https://doi.org/10.1016/j.econlet.2017.07.027", 
"type" => "ScholarlyArticle"
}
=> Separate format events

app/models/base.rb, app/models/concerns/cacheable.rb, app/models/related_identifier.rb, lib/tasks/related_identifier.rake, spec/models/related_url_spec.rb
- filters  import events from crossref.citations out
- check the Registration Agency of the DOIS to import from specific sources
- caches Member id and registrations agencies
=> Import events improvements 

app/jobs/usage_update_import_by_month_job.rb, app/jobs/usage_update_import_by_year_job.rb, app/models/usage_update.rb, lib/tasks/usage_update.rake, spec/models/usage_update_spec.rb
Create a rake to import usage reports by year. 
resolves: https://github.com/datacite/levriero/issues/68
=> rake to import usage reports

app/models/crossref.rb
Crossref started making its cited-by service citations available in eventdata since october https://docs.google.com/document/d/1uz9q2IKS7_kWebP19X2v7daBUr3duLKXmN6cWcMRkaY/edit#bookmark=id.r0biw9yctzj0 , however they did it under the same source-id as other crossref events. Theses event do not include datacite dois and thus might not be essential for Datacite at the moment.
Crossref told us how to filter them in Feb
https://www.eventdata.crossref.org/guide/service/query-api/
closes: _Add github issue that originated this PR_
See total-results 
https://api.eventdata.crossref.org/v1/events?source=crossref&from-occurred-date=2021-11-01&scholix=true 
and 
https://api.eventdata.crossref.org/v1/events?source=crossref&from-occurred-date=2021-11-01 (no filter)
- Be humble in the language and …
=> Filter citeb-by events from crossref agent

config/application.rb, spec/concerns/importable_spec.rb
closes: https://github.com/datacite/levriero/issues/114
=> add specs for the importable/parse_record method

config/application.rb, spec/fixtures/vcr_cassettes/RelatedUrl/class_methods/push_item/when_STAFF_ADMIN_TOKEN/is_invalid/is_not_set_will_only_request_logottino_for_those_related_identifiers_with_type_URL_.yml, spec/fixtures/vcr_cassettes/RelatedUrl/class_methods/push_item/when_STAFF_ADMIN_TOKEN/is_invalid/will_not_make_request_to_lagottino.yml, spec/lib/tasks/funder_identifier_rake_spec.rb, spec/models/related_url_spec.rb
closes: https://github.com/datacite/levriero/issues/119
=> add specs for funder identifier

.github/workflows/deploy.yml, .github/workflows/release.yml
https://github.com/codeclimate/test-reporter/issues/413#issuecomment-1079155787
closes: https://github.com/datacite/levriero/issues/167
=> fix simplecov and code climate compatibility

.github/workflows/deploy.yml, .github/workflows/parallel_ci.yml, .github/workflows/release.yml, Dockerfile, Gemfile, Gemfile.lock, app/models/heartbeat.rb, config/environments/development.rb, config/environments/production.rb, config/environments/stage.rb, spec/concerns/cacheable_spec.rb
closes: _Add github issue that originated this PR_
=> fix the ruby 3 upgrade

.github/workflows/deploy.yml, .github/workflows/release.yml
Update actions/cache to v4 in workflows ahead of deprecation of older versions
closes: #196 
=> Update actions/cache in workflows

app/models/crossref_funder.rb, spec/models/crossref_funder_spec.rb
closes: https://github.com/datacite/product-backlog/issues/187
=> Modify crossref funder to use events queue

app/models/crossref_import.rb, spec/models/crossref_import_spec.rb
closes: https://github.com/datacite/product-backlog/issues/188
=> modify crossref import to use the events queue

app/models/crossref_orcid.rb, spec/models/crossref_orcid_spec.rb
closes: https://github.com/datacite/product-backlog/issues/189
=> modify crossref orcid to use the events queue

app/models/crossref_related.rb, spec/models/crossref_related_spec.rb
closes: https://github.com/datacite/product-backlog/issues/190
=> modify crossref related to use the events queue

app/models/orcid_claim.rb, spec/models/orcid_claim_spec.rb
closes: https://github.com/datacite/product-backlog/issues/191
=> modify orcid claim to use events queue

app/models/related_arxiv.rb, spec/models/related_arxiv_spec.rb
closes: https://github.com/datacite/product-backlog/issues/192
=> modify related arxiv to use events queue

app/models/usage_update.rb, spec/models/usage_update_spec.rb
closes: https://github.com/datacite/product-backlog/issues/184
=> modify update usage to use the events queue

app/models/related_igsn.rb, spec/models/related_igsn_spec.rb
closes: https://github.com/datacite/product-backlog/issues/194
=> modify related igsn to use the events queue

app/jobs/usage_update_export_job.rb
closes: https://github.com/datacite/product-backlog/issues/196
=> remove logging from usage_update_export_job.rb

app/models/crossref.rb, spec/fixtures/vcr_cassettes/CrossrefFunder/push_item/sends_item_to_the_events_queue.yml, spec/models/crossref_spec.rb
closes: https://github.com/datacite/product-backlog/issues/197
=> modify crossref to use the events queue

app/models/related_identifier.rb
closes: https://github.com/datacite/levriero/issues/218
=> Remove related identifier error log
